baseurl = "https://docs.axoflow.com/axosyslog/"
buildDrafts = false
googleAnalytics = "G-3P6PW57YTF"

enableRobotsTXT = true

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-3P6PW57YTF"

[params]

url_latest_version = "https://docs.axoflow.com/axosyslog/"